# Generated by Django 4.2.14 on 2024-11-13 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Register created timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestampt')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(verbose_name='Content of the notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('user_interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
