# Generated by Django 4.2.14 on 2024-11-21 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_is_achived_post_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
