# Generated by Django 4.2.14 on 2024-12-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_postimage_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location_id',
        ),
    ]
