# Generated by Django 4.2.14 on 2024-12-10 22:08

from django.db import migrations, models
import django.db.models.deletion
import spotseeker.utils.location


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('post', '0005_remove_post_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ForeignKey(default=spotseeker.utils.location.populate_location, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
